{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "997e053e_9b9a02e6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1036512
      },
      "writtenOn": "2022-01-04T02:38:09Z",
      "side": 1,
      "message": "James,\n\nLooks like you\u0027ve got a merge conflict at this point. Also, you\u0027re failing CI validation, so I\u0027m pretty certain that Luca and others aren\u0027t likely to do a review until that\u0027s taken care of.",
      "revId": "a4018b9bf0a6dd2e407de1695d6b02226a7f2712",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}